/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module CARRY4(S, DI, CIN, CYINIT, CO, O);
  input CIN;
  wire CIN;
  output [3:0] CO;
  wire [3:0] CO;
  input CYINIT;
  wire CYINIT;
  input [3:0] DI;
  wire [3:0] DI;
  output [3:0] O;
  wire [3:0] O;
  input [3:0] S;
  wire [3:0] S;
  \$__GEMCARRY4_  _TECHMAP_REPLACE_ (
    .CIN(CIN),
    .CO(CO),
    .CYINIT(CYINIT),
    .DI(DI),
    .O(O),
    .S(S)
  );
endmodule

module DSP48E2(CLK, A, B, C, D, USE_PREADD, MODE, P);
  input [26:0] A;
  wire [26:0] A;
  input [17:0] B;
  wire [17:0] B;
  input [47:0] C;
  wire [47:0] C;
  input CLK;
  wire CLK;
  input [26:0] D;
  wire [26:0] D;
  input [1:0] MODE;
  wire [1:0] MODE;
  output [47:0] P;
  wire [47:0] P;
  input USE_PREADD;
  wire USE_PREADD;
  \$__GEMDSP_  _TECHMAP_REPLACE_ (
    .A(A),
    .B(B),
    .C(C),
    .CLK(CLK),
    .D(D),
    .MODE(MODE),
    .P(P),
    .USE_PREADD(USE_PREADD)
  );
endmodule

module SRLC32E(CLK, D, CE, A, Q, Q31);
  input [4:0] A;
  wire [4:0] A;
  input CE;
  wire CE;
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q31;
  wire Q31;
  \$__GEMSRL32_  _TECHMAP_REPLACE_ (
    .A(A),
    .CE(CE),
    .CLK(CLK),
    .D(D),
    .Q(Q),
    .Q31(Q31)
  );
endmodule

module macro_smoke(clk, a0, a1, d0, b0, b1, c0, mode, x, y, tap, ser_in, ser_en, acc0, acc1, sum, delayed, delayed31, scratch);
  wire [7:0] _0_;
  input [26:0] a0;
  wire [26:0] a0;
  input [26:0] a1;
  wire [26:0] a1;
  output [47:0] acc0;
  wire [47:0] acc0;
  output [47:0] acc1;
  wire [47:0] acc1;
  input [17:0] b0;
  wire [17:0] b0;
  input [17:0] b1;
  wire [17:0] b1;
  input [47:0] c0;
  wire [47:0] c0;
  wire [4:0] carry;
  input clk;
  wire clk;
  reg [7:0] cnt;
  input [26:0] d0;
  wire [26:0] d0;
  output delayed;
  wire delayed;
  output delayed31;
  wire delayed31;
  wire [3:0] \g_carry[0].co_i ;
  wire [3:0] \g_carry[1].co_i ;
  wire [3:0] \g_carry[2].co_i ;
  wire [3:0] \g_carry[3].co_i ;
  input [1:0] mode;
  wire [1:0] mode;
  wire [15:0] p;
  output [7:0] scratch;
  wire [7:0] scratch;
  input ser_en;
  wire ser_en;
  input ser_in;
  wire ser_in;
  output [16:0] sum;
  wire [16:0] sum;
  input [4:0] tap;
  wire [4:0] tap;
  input [15:0] x;
  wire [15:0] x;
  input [15:0] y;
  wire [15:0] y;
  assign _0_ = cnt + 8'h01;
  always @(posedge clk)
    cnt <= _0_;
  assign p = x ^ y;
  assign scratch = cnt ^ { x[3:0], y[3:0] };
  \$__GEMCARRY4_  \g_carry[0].u_c4  (
    .CIN(1'h0),
    .CO({ carry[1], \g_carry[0].co_i [2:0] }),
    .CYINIT(1'h0),
    .DI(x[3:0]),
    .O(sum[3:0]),
    .S(p[3:0])
  );
  \$__GEMCARRY4_  \g_carry[1].u_c4  (
    .CIN(carry[1]),
    .CO({ carry[2], \g_carry[1].co_i [2:0] }),
    .CYINIT(1'h0),
    .DI(x[7:4]),
    .O(sum[7:4]),
    .S(p[7:4])
  );
  \$__GEMCARRY4_  \g_carry[2].u_c4  (
    .CIN(carry[2]),
    .CO({ carry[3], \g_carry[2].co_i [2:0] }),
    .CYINIT(1'h0),
    .DI(x[11:8]),
    .O(sum[11:8]),
    .S(p[11:8])
  );
  \$__GEMCARRY4_  \g_carry[3].u_c4  (
    .CIN(carry[3]),
    .CO(\g_carry[3].co_i ),
    .CYINIT(1'h0),
    .DI(x[15:12]),
    .O(sum[15:12]),
    .S(p[15:12])
  );
  \$__GEMDSP_  u_dsp0 (
    .A(a0),
    .B(b0),
    .C(c0),
    .CLK(clk),
    .D(d0),
    .MODE(mode),
    .P(acc0),
    .USE_PREADD(1'h1)
  );
  \$__GEMDSP_  u_dsp1 (
    .A(a1),
    .B(b1),
    .C(48'h000000000000),
    .CLK(clk),
    .D(27'h0000000),
    .MODE(2'h1),
    .P(acc1),
    .USE_PREADD(1'h0)
  );
  \$__GEMSRL32_  u_srl (
    .A(tap),
    .CE(ser_en),
    .CLK(clk),
    .D(ser_in),
    .Q(delayed),
    .Q31(delayed31)
  );
  assign { carry[4], carry[0] } = { \g_carry[3].co_i [3], 1'h0 };
  assign \g_carry[0].co_i [3] = carry[1];
  assign \g_carry[1].co_i [3] = carry[2];
  assign \g_carry[2].co_i [3] = carry[3];
  assign sum[16] = \g_carry[3].co_i [3];
endmodule
