/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module \$__GEMCARRY4_ (S, DI, CIN, CYINIT, CO, O);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  input CIN;
  wire CIN;
  output [3:0] CO;
  wire [3:0] CO;
  input CYINIT;
  wire CYINIT;
  wire [4:0] Cv;
  input [3:0] DI;
  wire [3:0] DI;
  output [3:0] O;
  wire [3:0] O;
  input [3:0] S;
  wire [3:0] S;
  assign _00_ = _11_ & DI[0];
  assign _01_ = S[1] & Cv[1];
  assign _02_ = _08_ & DI[1];
  assign _03_ = S[2] & Cv[2];
  assign _04_ = _09_ & DI[2];
  assign _05_ = S[3] & Cv[3];
  assign _06_ = _10_ & DI[3];
  assign _07_ = S[0] & Cv[0];
  assign _08_ = ~ S[1];
  assign _09_ = ~ S[2];
  assign _10_ = ~ S[3];
  assign _11_ = ~ S[0];
  assign Cv[0] = CYINIT | CIN;
  assign Cv[1] = _07_ | _00_;
  assign Cv[2] = _01_ | _02_;
  assign Cv[3] = _03_ | _04_;
  assign CO[3] = _05_ | _06_;
  assign O[0] = S[0] ^ Cv[0];
  assign O[1] = S[1] ^ Cv[1];
  assign O[2] = S[2] ^ Cv[2];
  assign O[3] = S[3] ^ Cv[3];
  assign CO[2:0] = Cv[3:1];
  assign Cv[4] = CO[3];
endmodule

module \$__GEMDSP_ (CLK, A, B, C, D, USE_PREADD, MODE, P);
  wire [47:0] _00_;
  wire [26:0] _01_;
  wire [47:0] _02_;
  wire _03_;
  wire _04_;
  input [26:0] A;
  wire [26:0] A;
  wire [26:0] AD;
  input [17:0] B;
  wire [17:0] B;
  input [47:0] C;
  wire [47:0] C;
  input CLK;
  wire CLK;
  input [26:0] D;
  wire [26:0] D;
  wire [44:0] M;
  input [1:0] MODE;
  wire [1:0] MODE;
  output [47:0] P;
  reg [47:0] P = 48'h000000000000;
  input USE_PREADD;
  wire USE_PREADD;
  assign _01_ = $signed(A) + $signed(D);
  assign _02_ = $signed(P) + $signed({ M[44], M[44], M[44], M });
  assign M = $signed(AD) * $signed(B);
  always @(posedge CLK)
    P <= _00_;
  function [47:0] _09_;
    input [47:0] a;
    input [95:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _09_ = b[47:0];
      2'b1?:
        _09_ = b[95:48];
      default:
        _09_ = a;
    endcase
  endfunction
  assign _00_ = _09_(_02_, { C, M[44], M[44], M[44], M }, { _04_, _03_ });
  assign _03_ = MODE == 2'h1;
  assign _04_ = ! MODE;
  assign AD = USE_PREADD ? _01_ : A;
endmodule

module \$__GEMSRL32_ (CLK, D, CE, A, Q, Q31);
  input [4:0] A;
  wire [4:0] A;
  input CE;
  wire CE;
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q31;
  wire Q31;
  reg [31:0] sr = 32'd0;
  always @(posedge CLK)
    if (CE) sr <= { sr[30:0], D };
  wire [31:0] _2_ = sr;
  assign Q = _2_[A +: 1];
  assign Q31 = sr[31];
endmodule

module CARRY4(S, DI, CIN, CYINIT, CO, O);
  input CIN;
  wire CIN;
  output [3:0] CO;
  wire [3:0] CO;
  input CYINIT;
  wire CYINIT;
  input [3:0] DI;
  wire [3:0] DI;
  output [3:0] O;
  wire [3:0] O;
  input [3:0] S;
  wire [3:0] S;
  \$__GEMCARRY4_  _TECHMAP_REPLACE_ (
    .CIN(CIN),
    .CO(CO),
    .CYINIT(CYINIT),
    .DI(DI),
    .O(O),
    .S(S)
  );
endmodule

module DSP48E2(CLK, A, B, C, D, USE_PREADD, MODE, P);
  input [26:0] A;
  wire [26:0] A;
  input [17:0] B;
  wire [17:0] B;
  input [47:0] C;
  wire [47:0] C;
  input CLK;
  wire CLK;
  input [26:0] D;
  wire [26:0] D;
  input [1:0] MODE;
  wire [1:0] MODE;
  output [47:0] P;
  wire [47:0] P;
  input USE_PREADD;
  wire USE_PREADD;
  \$__GEMDSP_  _TECHMAP_REPLACE_ (
    .A(A),
    .B(B),
    .C(C),
    .CLK(CLK),
    .D(D),
    .MODE(MODE),
    .P(P),
    .USE_PREADD(USE_PREADD)
  );
endmodule

module SRLC32E(CLK, D, CE, A, Q, Q31);
  input [4:0] A;
  wire [4:0] A;
  input CE;
  wire CE;
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q31;
  wire Q31;
  \$__GEMSRL32_  _TECHMAP_REPLACE_ (
    .A(A),
    .CE(CE),
    .CLK(CLK),
    .D(D),
    .Q(Q),
    .Q31(Q31)
  );
endmodule

module macro_smoke(clk, a0, a1, d0, b0, b1, c0, mode, x, y, tap, ser_in, ser_en, acc0, acc1, sum, delayed, delayed31, scratch);
  wire [7:0] _0_;
  input [26:0] a0;
  wire [26:0] a0;
  input [26:0] a1;
  wire [26:0] a1;
  output [47:0] acc0;
  wire [47:0] acc0;
  output [47:0] acc1;
  wire [47:0] acc1;
  input [17:0] b0;
  wire [17:0] b0;
  input [17:0] b1;
  wire [17:0] b1;
  input [47:0] c0;
  wire [47:0] c0;
  wire [4:0] carry;
  input clk;
  wire clk;
  reg [7:0] cnt;
  input [26:0] d0;
  wire [26:0] d0;
  output delayed;
  wire delayed;
  output delayed31;
  wire delayed31;
  wire [3:0] \g_carry[0].co_i ;
  wire [3:0] \g_carry[1].co_i ;
  wire [3:0] \g_carry[2].co_i ;
  wire [3:0] \g_carry[3].co_i ;
  input [1:0] mode;
  wire [1:0] mode;
  wire [15:0] p;
  output [7:0] scratch;
  wire [7:0] scratch;
  input ser_en;
  wire ser_en;
  input ser_in;
  wire ser_in;
  output [16:0] sum;
  wire [16:0] sum;
  input [4:0] tap;
  wire [4:0] tap;
  input [15:0] x;
  wire [15:0] x;
  input [15:0] y;
  wire [15:0] y;
  assign _0_ = cnt + 8'h01;
  always @(posedge clk)
    cnt <= _0_;
  assign p = x ^ y;
  assign scratch = cnt ^ { x[3:0], y[3:0] };
  CARRY4 \g_carry[0].u_c4  (
    .CIN(1'h0),
    .CO(\g_carry[0].co_i ),
    .CYINIT(1'h0),
    .DI(x[3:0]),
    .O(sum[3:0]),
    .S(p[3:0])
  );
  CARRY4 \g_carry[1].u_c4  (
    .CIN(\g_carry[0].co_i [3]),
    .CO(\g_carry[1].co_i ),
    .CYINIT(1'h0),
    .DI(x[7:4]),
    .O(sum[7:4]),
    .S(p[7:4])
  );
  CARRY4 \g_carry[2].u_c4  (
    .CIN(\g_carry[1].co_i [3]),
    .CO(\g_carry[2].co_i ),
    .CYINIT(1'h0),
    .DI(x[11:8]),
    .O(sum[11:8]),
    .S(p[11:8])
  );
  CARRY4 \g_carry[3].u_c4  (
    .CIN(\g_carry[2].co_i [3]),
    .CO(\g_carry[3].co_i ),
    .CYINIT(1'h0),
    .DI(x[15:12]),
    .O(sum[15:12]),
    .S(p[15:12])
  );
  DSP48E2 u_dsp0 (
    .A(a0),
    .B(b0),
    .C(c0),
    .CLK(clk),
    .D(d0),
    .MODE(mode),
    .P(acc0),
    .USE_PREADD(1'h1)
  );
  DSP48E2 u_dsp1 (
    .A(a1),
    .B(b1),
    .C(48'h000000000000),
    .CLK(clk),
    .D(27'h0000000),
    .MODE(2'h1),
    .P(acc1),
    .USE_PREADD(1'h0)
  );
  SRLC32E u_srl (
    .A(tap),
    .CE(ser_en),
    .CLK(clk),
    .D(ser_in),
    .Q(delayed),
    .Q31(delayed31)
  );
  assign carry = { \g_carry[3].co_i [3], \g_carry[2].co_i [3], \g_carry[1].co_i [3], \g_carry[0].co_i [3], 1'h0 };
  assign sum[16] = \g_carry[3].co_i [3];
endmodule
